export * from './custom-types.d'
export { withChords } from './with-chords'
export { InlineChordPopover } from './inline-chord'
export { InputChordPopover } from './input-chord'
export { Popover, type PopoverRefs } from './components/popover'
export { InlineTapsItem as InlineChordElement, FixedTapsItem as FixedChordLeaf } from './components/taps-item'
